name: create-pdf


on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env: 
      MAIN_PATH: 'arxiv/'
      MAIN_NAME: 'E-Hypergraphs-arxiv'
      SLIDES_PATH: 'slides/'
      SLIDES_NAME: 'slides'
      EXTENDED_ABSTRACT_PATH: 'extended_abstract/'
      EXTENDED_ABSTRACT_NAME: 'EGraphsExtendedAbstract'
      CLOSED_MONOIDAL_PATH: 'closed_monoidal/'
      CLOSED_MONOIDAL_NAME: 'closed_monoidal'
      LICS25_CLOSED_PATH: 'LICS_2025/e_graphs_with_bindings/'
      LICS25_CLOSED_NAME: 'E-graphs-with-bindings'
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Set release name
        id: name
        run: echo "name=$(date +'%Y-%m-%d-%H%M')" >> $GITHUB_OUTPUT
      - name: Create a new release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: ${{ steps.name.outputs.name }}
          tag_name: ${{ steps.name.outputs.name }}
# Compile monoidal e-graphs paper 
      - name: latexmk ${{env.MAIN_NAME}}
        if: always()
        uses: dante-ev/latex-action@latest
        with:
            root_file: ${{env.MAIN_NAME}}.tex
            args: -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode -latexoption=-shell-escape
            working_directory: ${{env.MAIN_PATH}}
# Compile monoidal e-graphs paper 
      - name: latexmk ${{env.EXTENDED_ABSTRACT_NAME}}
        if: always()
        uses: dante-ev/latex-action@latest
        with:
            root_file: ${{env.EXTENDED_ABSTRACT_NAME}}.tex
            args: -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode -latexoption=-shell-escape
            working_directory: ${{env.EXTENDED_ABSTRACT_PATH}}
# Compile slides
      - name: latexmk ${{env.SLIDES_PATH}}${{env.SLIDES_NAME}}
        if: always()
        uses: dante-ev/latex-action@latest
        with:
          root_file: ${{env.SLIDES_NAME}}.tex
          args: -xelatex -latexoption=-file-line-error -latexoption=-interaction=nonstopmode -latexoption=-shell-escape -latexoption=-pdf
          working_directory: ${{env.SLIDES_PATH}}
# Compile closed_monoidal
      - name: latexmk ${{env.CLOSED_MONOIDAL_PATH}}${{env.CLOSED_MONOIDAL_NAME}}
        if: always()
        uses: dante-ev/latex-action@latest
        with:
          root_file: ${{env.CLOSED_MONOIDAL_NAME}}.tex
          args: -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode -latexoption=-shell-escape
          working_directory: ${{env.CLOSED_MONOIDAL_PATH}}
# Compile lics closed 
      - name: latexmk ${{env.LICS25_CLOSED_PATH}}${{env.LICS25_CLOSED_NAME}}
        if: always()
        uses: dante-ev/latex-action@latest
        with:
         root_file: ${{env.LICS25_CLOSED_NAME}}.tex
         args: -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode -latexoption=-shell-escape
         working_directory: ${{env.LICS25_CLOSED_PATH}}
# Upload all pdfs
      - name: Upload monoidal e-graphs the release
        if: always()
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{env.MAIN_PATH}}${{env.MAIN_NAME}}.pdf
          asset_name: arxiv.pdf
          asset_content_type: pdf
      - name: Upload extended abstract the release
        if: always()
        uses: actions/upload-release-asset@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ${{env.EXTENDED_ABSTRACT_PATH}}${{env.EXTENDED_ABSTRACT_NAME}}.pdf
            asset_name: EGraphs2024ExtendedAbstract.pdf
            asset_content_type: pdf
      - name: Upload slides to the release
        if: always()
        uses: actions/upload-release-asset@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ${{env.SLIDES_PATH}}${{env.SLIDES_NAME}}.pdf
            asset_name: slides.pdf
            asset_content_type: pdf
      - name: Upload closed monoidal notes PDF to the release
        if: always()
        uses: actions/upload-release-asset@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ${{env.CLOSED_MONOIDAL_PATH}}${{env.CLOSED_MONOIDAL_NAME}}.pdf
            asset_name: closed_monoidal.pdf
            asset_content_type: pdf
      - name: Upload e-graphs with bindings PDF to the release
        if: always()
        uses: actions/upload-release-asset@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ${{env.LICS25_CLOSED_PATH}}${{env.LICS25_CLOSED_NAME}}.pdf
            asset_name: LICS25Closed.pdf
            asset_content_type: pdf
      - name: Delete older releases
        if: always()
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 1
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
