name: create-pdf


on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env: 
      MAIN_PATH: 'arxiv/'
      MAIN_NAME: 'E-Hypergraphs-arxiv'
      EXT_ABSTRACT_PATH: 'extended_abstract/'
      EXT_ABSTRACT_NAME: 'EGraphsExtendedAbstract'
      SLIDES_PATH: 'slides/'
      SLIDES_NAME: 'slides'
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Set release name
        id: name
        run: echo "name=$(date +'%Y-%m-%d-%H%M')" >> $GITHUB_OUTPUT
      - name: Create a new release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: ${{ steps.name.outputs.name }}
          tag_name: ${{ steps.name.outputs.name }}
# Compile full paper 
      - name: pdflatex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: ${{env.MAIN_NAME}}.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
          working_directory: ${{env.MAIN_PATH}}
      - name: bibtex main
        if: always()
        uses: dante-ev/latex-action@latest
        with:
          root_file: ${{env.MAIN_NAME}}.aux
          compiler: bibtex
          args:
          working_directory: ${{env.MAIN_PATH}}
      - name: pdflatex main
        if: always()
        uses: dante-ev/latex-action@latest
        with:
          root_file: ${{env.MAIN_NAME}}.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
          working_directory: ${{env.MAIN_PATH}}
      - name: pdflatex main
        if: always()
        uses: dante-ev/latex-action@latest
        with:
          root_file: ${{env.MAIN_NAME}}.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
          working_directory: ${{env.MAIN_PATH}}
# # Compile submission
#       - name: pdflatex E-Hypergraphs-LICS24 
#         uses: dante-ev/latex-action@latest
#         with:
#           root_file: E-Hypergraphs-LICS24.tex
#           compiler: pdflatex
#           args: -interaction=nonstopmode -shell-escape 
#       - name: bibtex E-Hypergraphs-LICS24
#         if: always()
#         uses: dante-ev/latex-action@latest
#         with:
#           root_file: E-Hypergraphs-LICS24.aux
#           compiler: bibtex
#           args:
#       - name: pdflatex E-Hypergraphs-LICS24
#         if: always()
#         uses: dante-ev/latex-action@latest
#         with:
#           root_file: E-Hypergraphs-LICS24.tex
#           compiler: pdflatex
#           args: -interaction=nonstopmode -shell-escape
#       - name: pdflatex E-Hypergraphs-LICS24
#         if: always()
#         uses: dante-ev/latex-action@latest
#         with:
#           root_file: E-Hypergraphs-LICS24.tex
#           compiler: pdflatex
#           args: -interaction=nonstopmode -shell-escape
# # Compile review response
#       - name: pdflatex Reviews-response.tex
#         uses: dante-ev/latex-action@latest
#         with:
#           root_file: Reviews-response.tex
#           compiler: pdflatex
#           args: -interaction=nonstopmode -shell-escape
# Compile Extended Abstract
      - name: pdflatex ${{env.EXT_ABSTRACT_NAME}}
        uses: dante-ev/latex-action@latest
        with:
          root_file: ${{env.EXT_ABSTRACT_NAME}}.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
          working_directory: ${{env.EXT_ABSTRACT_PATH}}
      - name: bibtex ${{env.EXT_ABSTRACT_PATH}}${{env.EXT_ABSTRACT_NAME}}
        if: always()
        uses: dante-ev/latex-action@latest
        with:
            root_file: ${{env.EXT_ABSTRACT_NAME}}.aux
            compiler: bibtex
            args:
            working_directory: ${{env.EXT_ABSTRACT_PATH}}
      - name: pdflatex ${{env.EXT_ABSTRACT_NAME}}
        if: always()
        uses: dante-ev/latex-action@latest
        with:
            root_file: ${{env.EXT_ABSTRACT_NAME}}.tex
            compiler: pdflatex
            args: -interaction=nonstopmode -shell-escape
            working_directory: ${{env.EXT_ABSTRACT_PATH}}
      - name: pdflatex ${{env.EXT_ABSTRACT_PATH}}${{env.EXT_ABSTRACT_NAME}}
        if: always()
        uses: dante-ev/latex-action@latest
        with:
            root_file: ${{env.EXT_ABSTRACT_NAME}}.tex
            compiler: pdflatex
            args: -interaction=nonstopmode -shell-escape
            working_directory: ${{env.EXT_ABSTRACT_PATH}}
# Compile slides
      - name: latexmk ${{env.SLIDES_PATH}}${{env.SLIDES_NAME}}
        if: always()
        uses: dante-ev/latex-action@latest
        with:
          root_file: ${{env.SLIDES_NAME}}.tex
          latexmk_shell_escape: true
          latexmk_use_xelatex: true
          args: -interaction=nonstopmode -shell-escape
          working_directory: ${{env.SLIDES_PATH}}
# Upload both pdfs
      - name: Upload the PDF to the release
        if: always()
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{env.MAIN_PATH}}${{env.MAIN_NAME}}.pdf
          asset_name: arxiv.pdf
          asset_content_type: pdf
      - name: Upload the PDF to the release
        if: always()
        uses: actions/upload-release-asset@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{env.EXT_ABSTRACT_PATH}}${{env.EXT_ABSTRACT_NAME}}.pdf
          asset_name: ExtendedAbstract.pdf
          asset_content_type: pdf
      - name: Upload the PDF to the release
        if: always()
        uses: actions/upload-release-asset@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ${{env.SLIDES_PATH}}${{env.SLIDES_NAME}}.pdf
            asset_name: slides.pdf
            asset_content_type: pdf
      - name: Delete older releases
        if: always()
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 1
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
